### ISSUE TITLE
Minimum Page Size

### ISSUE THREAD

**Issue by GouldenJen** [daisy/ebraille#110]
- GitHub ticket: #41	
- Requested metadata: Minimum page size	
- NLS Dublin Core Element: N/A			
- Notes from GitHub ticket: This will allow the reading system to know if it's even possible to display or emboss the file using the current hardware.
Would be determined by any sections that are preformatted and the necessary display size and file type of tactile graphics.
Would be on the reading system to interpret this information and know the limitations of the hardware.	
- Notes from metadata team: Is this need covered by bri:pageLength and brl:lineLength or is additional metadata needed for this?

**Comment by wfreeman-aph** [comment]
I think we need the minimum page size more than any other information about line length or page size. Line length or page size could be file specific metadata about certain tactile graphics, so something to let software know how to, and if it can, render a graphic- similar to how the size of images are indicated for displaying as a part of web pages. However, the minimum size at least helps users and software know what will be possible in processing the file. If a file, for instance, requires 40 cells per line, a smaller display or embosser could at least warn the user of this discrepancy while still attempting to reproduce it.

If a file is fully reflowable, then instead of a number, a word like "reflowable" could be given instead. Every book will likely need at least 10 cells per line, so while that could be established as a "universal minimum" it's an assumption I can't back up with data, so that's why I'd suggest using the term "reflowable" instead.

Minimum size would otherwise mean that the contents of the file would not be digestible at a line length less than that value. Some examples would be books for higher math, books with a lot of spatial materials that cannot be reflowed, or a very specific work of spatial poetry. I think software could propose a minimum based on the largest symbol sequence or presence of spatial materials but the user would likely need to make the final call and it'd be a guide more than something that is absolutely understood as true.

**Comment by wfree-aph** [comment]
The values minimumCells and minimumLines are both reflected in the [first draft of the specification](https://github.com/daisy/ebraille/blob/main/index.html) under section A.5.3 and A.5.4 respectively. Closing this as completed.

**Comment by mattgarrish** [comment]
They are optional metadata so they aren't going to be detailed in the main metadata section. I can add a reference to the vocabulary from the additional metadata section, though.
