### ISSUE TITLE
Identifier metadata

### ISSUE THREAD

**Issue by nicolegaines** [daisy/ebraille#111]
Should all eBraille files have a unique identifier? This would be useful for libraries and for searching for materials in systems. For eBraille produced for published books, the ISBN would be the best Identifier. Are there additional schema that should be accepted/optional? Should the element be repeating, in the case where a producer wants to include another Identifier (such as an accession number) and an ISBN? Do we want to prescribe a schema for materials not generated from books published with an ISBN? Do we need to accommodate a unique Identifier for separate eBraille files if multiple transcribers are creating different volumes, which will then be merged at the end of production?

**Comment by mattgarrish** [comment]
The problem with unique identifiers, as we found with epub, is that there is no way to ensure they are unique. Absent an isbn, issn, or similar, people will just put whatever they feel like in the field to make the error go away. Consequently, a lot of epubs have the unique identifier "1".

The publication manifest specification requires a url as the unique identifier, but I'm not sure this greatly improves things as it probably just leads to "https://example.com" instead of "1" when you don't have a unique domain to associate with the publication.

That's not to say we shouldn't accommodate (unique) identifiers, but I'm not sure what benefit there is in requiring them if it just forces authors to make them up.

**Comment by wfreeman-aph** [comment]
It was agreed at the 11/14/24 meeting to keep this metadata as optional. The recommendation will be that the identifier is not in any way universally managed for the entire file type and instead will be localized to the organization creating the files. So, for example, RNIB will have its own scheme and APH will have their own scheme and so on. This identifier then will be most useful for the organization creating the file and will be on them to manage. It's also likely that even the file author will not be responsible for adding this metadata and instead if will be added by a manager of the file database or library.
