### ISSUE TITLE
Metadata: Extent of Excerpt or Incomplete Transcription

### ISSUE THREAD

**Issue by shepazu** [daisy/ebraille#128]
- Requested metadata: Indication on which sections of an external document are included in this document
- NLS Element: `dc:Description`
- Notes from GitHub ticket: 
  - When an eBraille file contains only certain sections of a book, the metadata should reflect the extent of the partial transcription (e.g., "Contains only Chapters 1-5 of the source book.").

## References:
- Original issue: #98

**Comment by shepazu** [comment]
This may be usefully described in `dc:Description`, but if this is a common case (as I suspect), perhaps there should be a more formal metadata element for it?

**Comment by shepazu** [comment]
If a document contains excerpts from multiple other documents/books, as is common in university coursework, maybe this should be captured too?

**Comment by wfreeman-aph** [comment]
I don't think that this is a very common use case but what's interesting about it to me is that eBraille obscures this problem. Before you'd have a folder and upon opening the folder, you'd know what volumes were included. Now that information is buried inside a zipped bundle that your average user cannot penetrate.

I think we have to have some kind of metadata that covers this need but we'd need a standardized way to define it. I don't think volumes are sufficient since they have no bearing on the original work and one cannot surmise what volumes 1-10 really means even if a braille expert. It should be based on print pages, in my opinion. Like "Pages 1-336 of 832" or something like that. If the entire work is included, it could instead read "Full".

Also between `dc:Description` and having something more specific, I think we're better being more specific. I don't know what term would be preferred here. Is something like `completeness` sufficient?

**Comment by wfreeman-aph** [comment]
It was agreed at the 11/14/24 meeting to keep this metadata in the MVP. The goal would be to have in the initial spec, binary options of either "partial" or "complete". In our recommendations about the spec, we can make it clear that "complete" does not literally mean every single word has been transcribed but simply that the transcription can be considered complete as it covers the majority of the original work. Examples would include the transcription of a novel where the picture of the author is omitted. You wouldn't want that work to be classified as "partial" because a single image was ignored and not described.

Additionally, at a later date, we can add an additional aspect to this that allows the user to designate how much of the original work has been completed. It was discussed at that same meeting that NISO will be standardizing metadata on content that has been remediated and they should have something that will work for our needs here and we can adopt or modify that for our own purposes after it is released.
