### ISSUE TITLE
Metadata: Identifier schema

### ISSUE THREAD

**Issue by shepazu** [daisy/ebraille#129]
- Requested metadata: Identifier (unique?)
- NLS Element: `dc:Identifier`
- Notes from Excel file: 
  - The Identifier schema could be based on the ISBN or a producer accession number if source material has no ISBN. 
  - Needs to be able to accommodate when one ISBN is split between several eBraille files (separate volumes for embossing)?

Note: A [DOI](https://www.doi.org/the-identifier/what-is-a-doi/) (digital identifier of an object) could be used for this.

As with #120, DCMI recommends that identifiers should be in a `dcterms:isPartOf` entry, and the [should be encoded in values of DC properties as value URIs](https://www.dublincore.org/specifications/dublin-core/dc-citation-guidelines/#52-identifiers). A DOI would be encoded in the form `info:doi/`. For example, `info:doi/10.1045/july99-caplan`.

## References:
- See #111 for related discussion of unique identifiers
- See #120 for related discussion of ISBN

**Comment by shepazu** [comment]
A given document may have multiple unique identifiers, especially if they are registered in different systems. Perhaps this should be an array of objects, rather than a single value. Each object could have a label for intended purpose or audience.

**Comment by wfreeman-aph** [comment]
I think our big issue with trying to use anything other than ISBN is that people will not want to do it. ISBN seems like the easiest option. That said, I would want to just call the item "ISBN" and not "identifier" so it is clear how it should be used. The issue here is that you don't want to confuse the original work with the braille transcription. So maybe it's ISBN and we attach a hyphen and "br"? Not sure. Then if the original work has no ISBN, you just put N/A?

**Comment by wfreeman-aph** [comment]
Closing this duplicate in favor of #111. The discussion here is valuable and will not be lost as it is referenced in that other ticket.
