### ISSUE TITLE
Best practice tagging: problem with Braille Grades

### ISSUE THREAD

**Issue by jrbowden** [daisy/ebraille#137]
The Best Practice for Tagging document, Braille Grade section currently states:
--
Reserved class values:
grade-0, grade-1, grade-2
Note that terms for braille grade vary throughout the world and that grade-related class values do not directly correlate to how a local region may understand the terms. Hence, in a region where uncontracted braille is called Grade 1, grade-0 is preferred for the class name so that these terms may be better understood internationally. Basically, one should use the least value class for the least contracted grade of braille and move up in value from there.
--

I am very concerned at the apparent disconnect here between the suggested reserved words and their real world meaning. This is almost inevitably going to lead to confusion.
As stated in #105 the suggested reserved words do have actual meaning to transcribers and readers alike, though these may vary across regions.

The main reasons for advertising the braille grade are:
- to alert the user to the actual braille code in use
- to instruct a back-translator how to convert back to print

We currently do not have a defined mechanism for doing either. It would likely partly be done in metadata and partly in CSS.

If this is so, then the class  to show a change of braille code - note, braille code, not just braille grade - will point to CSS and it is the CSS that will fully define the braille code being used. Therefore, I submit, there should be no reserved words for braille grade, it is up to the CSS mark-up.

I could quite validly write:
- ``<p class="uncontracted"> ...``
- ``<span class="g1brl">...``
- ``<div class="braille-grade-1">...``
- ``<h1 class="jobtoken_4239857">...``
...

(obviously, the last example here sounds totally machine-generated and would not be "recommended best practice", but it is still a valid class name).

The relevant class definitions in the CSS should contain the information needed for the braille code and grade.

Note, another "problem" with the current proposal is to ask what would happen with a book that contains "graduated" braille: that is, a book that begins with uncontracted braille, then increasingly introduces more and more contractions, until at the end it is fully contracted? With the current proposal, this book would start at grade-0 and end up at, say, grade-15, while actually it means (in the English Braille sense) going from uncontracted (grade 1) to contracted (grade 2).

Finally, what about braille codes which don't have a "grade" as such? This would include music, Nemeth, and many languages which only have one grade.

I submit, there should be no reserved words for braille code or grade, instead we need a mechanism to define both, in metadata and CSS.

**Comment by wfreeman-aph** [comment]
Thanks for the comment @jrbowden. My thinking here was that the use of tagging for braille grades would only happen if the document contained more than one grade. If the entire document is contracted, no need to tag braille grade. So that should satisfy the potential issue with codes that don't use grades or only have one grade but let me know if I misunderstood.

In a work that began uncontracted and slowly introduced contractions, you would only need to tag the parts that changed, so you'd either tag the uncontracted sections or the contracted sections. The author would set their translation to either contracted or uncontracted and then tag anywhere that there was an exception to the table that they initially set, so whichever set of text is the exception, that's the one that would be tagged in the markup. That's how I think it would work in software. A user could decide to manually six-key the exception parts and the software would probably not be able to catch that but I don't think we can design the spec people not applying proper markup to their documents.

I feel like we must tag braille grades. If we don't, it'll make backtranslation that much more difficult. That's why I don't feel we can leave it to CSS and metadata but please let me know what you had in mind.

On the use of [zero-based numbering,](https://en.wikipedia.org/wiki/Zero-based_numbering#:~:text=Zero%20is%20the%20lowest%20unsigned,science%20often%20begin%20with%20zero.) this is something I don't feel particularly strong about but it is how numbering tends to work in programming. It's not something the average user will ever see but will instead be something which is managed by software. The user interface could use plain language for the terms involving braille grade but the markup in the background will use whatever terms we agree upon (ideally).

**Comment by jrbowden** [comment]
I absolutely agree that things should be properly tagged up, I submit that it is the vocabulary of CSS and HTML tags that defines the behaviour, not class names.

I am thinking that it is likely that each production system (and organisation) will develop their own CSS sheet using class names that make sense to them. What matters here is what's in the CSS, not the class names themselves.

Example: The standard Duxbury templates for BANA and UKAAF both have a style for a standard paragraph. Effectively the styles do the same thing, but they are called very different names.
OK, granted in HTML we'd have a ``p`` tag as well, but the class name, as demonstrated by Duxbury, does not matter.
Therefore I submit it should not matter for eBraille either.
We need to work out a way to specify braille code, probably a tag, or CSS, or combination. It will be a combination of language (if any), grade (if any) and any special considerations.

**Comment by wfreeman-aph** [comment]
@jrbowden Apologies for the very long delay in replying. The issue here, I think, is that while braille is different across regions, there are ultimately only so many kinds of formatting for any braille region to deal with. Take paragraphs, there's indented, blocked, and maybe some kind of offset version of both of those. Each may be handled differently depending on the braille region but the classes for them can be the same.

Then, within CSS, there's only so many things you can do with braille characters to create formatting. There's blank lines, there's types of indention, there's putting in a specific braille character to signify a particular thing like a box or a heading. So the limited number of types of formatting both for print and braille can use a common language across software and simplify the creation of both tools to make eBraille files and to open and read eBraille files.

And, again, the other commonality here is that the user will never know what class names are being used. The UK can continue to call its different kinds of formatting whatever it wants and so can the US, and so can any other braille region and the software's user interface will reflect these commonly understood names. The only place where this information is pertinent is in the background of the software that is being used to create these files. The user will never know what vocabulary is being used so it is really irrelevant if it matches what the user expects. Having common class names as much as we can will only make software development easier.

**Comment by jrbowden** [comment]
I think I am obviously missing something here: surely when an author creates a file, they will want to pick from a list of, effectively styles. This list is custom, depending on the region and house style of the producing agency.

Also, when a file is rendered, whenever the software encounters a class, it must look up the details of what that class means from the CSS. It cannot assume what to do from the class name aloone.

In both cases, I don't see what advantage or saving there is in having defined names for the classes, as both the authoring and rendering software must look up from the class what the speicific instructions are in the CSS.
What am I missing?

Where I do see an advantage of having a defined name is, if there is no specific HTML tag for a particular thing and we specifically want to allow a user to navigate to that thing, then a class name is a secondary way to navigate. This links to issue #1 - e.g. allowing a user to navigate to a transcriber note. I still think it would be helpful to establish a list for issue #1 so we can gauge where specific classes would be needed.

In the specific case of marking braille grade, I don't think we can use the ability to navigate to a braille grade, especially as the class names as proposed don't exactly specify the meaning of the braille grade. therefore specific classes of grade-0 etc aren't particularly useful.

Again, I must be missing something...?

**Comment by wfreeman-aph** [comment]
I think the disconnect here is that when a user of braille transcription software is making an eBraille file, they will be interacting with a graphical user interface (GUI). That GUI can say whatever it needs to in order to most clearly communicate local naming conventions. Then the software can use whatever tags and class names it needs to in the file in order to most clearly be understood by reading software all around the world. The main issue is that the GUI and the file don't need to use the same naming conventions. In the file it can be braille-grade-1 and in the GUI, it can be uncontracted.

**Comment by jrbowden** [comment]
From discussions at eBraille meeting 13 Feb 2024:

We agree the reasons for using reserved class names are:

- To define an object which doesn't have an HTML tag, e.g. a line number, transcriber note.
- If needed for navigation to such items, e.g. navigate directly to a transcriber note
- To show/hide such items - e.g. show/hide print page indicators.
- interoperability - so a different stylesheet can be swapped in to reformat a document (issue #90)
- To better facilitate consistency amongst authoring and software development

**Comment by wfreeman-aph** [comment]
I'm going to close this issue but please let me know if you'd like me to reopen it for any further discussion.
