### ISSUE TITLE
Don't advise using `<br/>` to break long headings into multiple lines

### ISSUE THREAD

**Issue by bertfrees** [daisy/ebraille#211]
The "Multiline heading" example in tagging best practices contains `<br/>` elements. This is perfectly valid but might create the perception that the `<br/>` are needed to balance the lines. This is not true. In the styling best practices we suggest using `text-wrap: balance` to automate the balancing. We should only advice using `<br/>` when the automatic breaking results in illogical breaks.

**Comment by wfree-aph** [comment]
@bertfrees It's occurring to me now why `text-wrap: balance` isn't always the correct solution. The issue is not just line wrapping. It's making the breaks happen at logical points. In BANA, you don't just want to wrap anywhere, you want the breaks to make sense, even if the two lines are not balanced. However, I can see why `text-wrap: balance` should still be included because there are probably regions where logical breaks are not considered. Different regions will balance precision and cost differently.

This aspect didn't occur to me until I was working on #229. As I read the braille saying "logical points," I remembered what had been alluding me. I'll still correct for #229 since the example concerns `text-wrap: balance` but I think we need both `wbr` and `text-wrap: balance`.

What do you think? Is there a way to include both in a single example so that different braille regions can utilize the same heading and have their region's rules respected?

**Comment by wfree-aph** [comment]
@bertfrees Thanks for the reference in the styling document for the BANA rules. I've reread and you are correct that it says logical and balanced. I've always interpreted that to mean that you divide at a logical point while maintaining some level of balance, which would still mean you might have a logical break that is not perfectly balanced. So, you wouldn't force a "logical" break that forced the first line to be 20 characters and the second line to be 5 characters but you might force one that made the lines 20 characters and 15 characters, even if 18 and 18 would be more balanced.

**Comment by bertfrees** [comment]
Yes, I also interpreted it that way, and I think we can (and should) include both in the best practices. It's also what I said in my first comment:

> We should only advice using `<br/>` when the automatic breaking results in illogical breaks.

I would not try to combine them in a single example though. They're two different things IMO.

More ideas on this in https://github.com/daisy/ebraille/pull/253#issuecomment-2306652137.

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/ebraille/pull/253
