### ISSUE TITLE
Published 1.0: Links to Best Practices pages don't go to published URLs

### ISSUE THREAD

**Issue by Menelion** [daisy/ebraille#242]
If you read the [Published Working Draft 1.0](https://daisy.github.io/ebraille/published/1.0/), there are links to Tagging and Styling Best Practices. Those lead to nowhere (404). The pages are available, for example, at https://daisy.github.io/ebraille/best-practices/styling/.

I would be glad to help you and send a PR, but I need to know what to do: correct the URLs in the `Published` folder or just copy best practices pages there.

**Comment by mattgarrish** [comment]
Thanks for this report. Because the best practices haven't been officially published yet, the current URLs only work in the editor's draft. I'll put in a temporary redirect for now to make the published draft links work, but we can't properly address this until we publish the guides.

**Comment by Menelion** [comment]
Great! If you need any help, please feel free to ask. I'm now reading the published 1.0 draft, and I'm impressed by the amount of work and by quality of decisions made. I'm super enthusiastic about eBraille and I hope we'll see it soon in more and more publications.

**Comment by wfree-aph** [comment]
Now that these links work and the user doesn't get a 404, I am going to close this issue as resolved. If we have future issues, the issue can be reopened or we can make a new one.

**Comment by mattgarrish** [comment]
Reopening as this is still a problem until we publish the first drafts of the best practice guides. What's in place right now is just a redirect hack to the editor drafts. We need to fix the links when we're ready to publish all three documents again.

**Comment by wfree-aph** [comment]
@mattgarrish My thinking was that the issue should reflect what we want done, so in this case we could close this one and, since it is needed, open an issue that reflects the need to change the redirect hack to the actual link after publishing. Just know how easily I miss issues because of the title.

**Comment by mattgarrish** [comment]
You can edit the title at the top of the page if you don't feel it reflects the issue anymore. (I've tweaked this one.)

I prefer to keep an issue open until it's fully resolved rather than split the actions to take across issues. It just makes it easier to track back through the conversation to understand what we've done so far and why. I've got this one on my radar to fix when the time comes.
