### ISSUE TITLE
Change example "markers" to headings

### ISSUE THREAD

**Issue by bertfrees** [daisy/ebraille#256]
so that screen reader users can navigate to it more easily. (Suggestion from @jrbowden.)

The examples are currently `<div class="marker">`.

**Comment by bertfrees** [comment]
@mattgarrish Could we do this with JavaScript? Or do you have a better idea?

**Comment by mattgarrish** [comment]
We can run a postprocessing step on the files. I'm just trying to find out why respec doesn't make them headings. Notes have headings using aria attributes, for example, so it's not like no one's thought of these cases. I did see something in the respec tracker about permalinks inside headings causing problems for AT. I wonder if that's why examples have been left without. I might file an issue and see what response I get.

**Comment by bertfrees** [comment]
Thanks for filing the respec issue!
