### ISSUE TITLE
Styling best practices: drop the section on "automatic numbering" for now

### ISSUE THREAD

**Issue by bertfrees** [daisy/ebraille#273]
Since we are probably going to recommend hard-coding the numbers/bullets of list items and headings into the text content, we might as well drop the section on "Automatic numbering" for now. There is nothing else to be numbered: we haven't covered braille page numbers and footnotes in the best practices yet (deliberately omitted for now because of bad/lacking support in browsers).

By the way, we might need an example of `list-style-type: none` in the best practices.

**Comment by egli** [comment]
Are you sure we are going to recommend hard-coding the numbers/bullets? At the last meeting it sounded that we at least have to have a mechanism for generating page numbers. And if we already know how to generate numbers we might as well use it for lists.

**Comment by bertfrees** [comment]
I was thinking we could add the section as soon as we cover page numbers in the best practices document.

**Comment by wfree-aph** [comment]
Something else that may not be clear is that we're putting the braille symbols for the numbers, bullets, etc. inside the correct ul and ol tags. So we'll still have the semantic markup and we'll use CSS to ensure we don't get double list prefixes. I get why so many folks in the working group are interested in utilizing the automatic numbers and bullets provided by HTML, but we need to have more discussion and input from people outside the working group about how these will work in practice.

Braille's need here comes from the need to utilize the specific symbols within each particular work, rather than just the default automatic symbols that one can usually rely on. Even if we used automatic symbols, we'd still need to tell the reading system which symbol to generate- so on that level, we'd still be hard coding it, just with an extra step and some added uncertainty. As well as making development more complicated for reading systems.

I like the suggestion of identifying the hard coded list prefixes with its own markup (in addition to the correct ul or ol tags), as that would preserve the integrity of the braille transcription while also giving flexibility to those that desire it.
