### ISSUE TITLE
Breaking Navigation further

### ISSUE THREAD

**Issue by avneeshsingh** [daisy/ebraille#42]
Starting from navigation use case in #41 

We should breakdown navigation further:
* Link triggered navigation. It works within the current file as well as across the files.
* Reading system aided navigation.

The link triggered navigation includes go to a section, go to a page, go to a landmark etc. DAISY and EPUB provide explicit structure of TOC, pagelist and landmarks for these three. Do we expect the same from EBraille?

Reading system aided navigation is based on the actions taken by reading system on the basis of semantics. For example move to next/previous headings, next/previous paragraph, table navigation etc. For this we mainly need to ensure correct semantics and write a reading system guidance document for helping reading system in implementing these.

**Comment by jrbowden** [comment]
Reading system also needs a Back command to return to a previous position. e.g. following a link to a footnote then want to resume reading the main text.

**Comment by wfree-aph** [comment]
The inclusion of links and markup in the [first draft of the specification](https://github.com/daisy/ebraille/blob/main/index.html) make both kinds of navigation possible. It will be up to reading systems to implement support but since the first spec is based on the EPUB packaging format, this should be easier than if we hadn't based it on an existing specification. Closing this as resolved.
