### ISSUE TITLE
Tags for Emphasis

### ISSUE THREAD

**Issue by wfreeman-aph** [daisy/ebraille#72]
There are several approaches to emphasis, also known as font attributes, already available in HTML. One can use largely visual methods like \<i> for italics, \<b> for bold, and \<u> for underline. Best practices for accessibility say to use \<em> for italics and \<strong> for bold. I am not sure if there would be a preference within eBraille but we'd likely want to follow best practices to assist in screen reader accessibility.

\<mark> is a kind of emphasis in HTML that means that the text is meant to be highlighted and could be used to represent the generic kinds of emphasis, like the catchall transcriber defined typeforms that are found in UEB. \<mark> can be modified with CSS to represent multiple kinds of emphasis.

Additionally, \<span> with additional elements could be used for as a catchall for unrepresented kinds of emphasis that could be found in other braille regions.

Questions: Is there a reason to use \<i> instead of \<em> or \<b> instead of \<strong>? Is \<mark> suitable as a catchall for other types or would a \<span> be preferable>? Are there other considerations here that are missing? What kinds of emphasis are used in braille internationally?

**Comment by skntkacm** [comment]
As to the Slovak rules of emphasizing, we are rebuilding them and will follow BANA rules as much as possible. 
I agree on copying best practices and using tags which screen readers do use. 
We do not have any specific emphasizing rules or requirements in Slovakia.

**Comment by jrbowden** [comment]
I agree to use standard tags where possible.
One consideration: do we need to somehow mark the braille characters which indicate the emphasis mark, as well as the fact that a piece of text is emphasised?
I guess we need to decide the purpose of marking up the emphasised text, is it:
1. For purposes of back-translation, and/or
2. For purposes of show/hide braille indicators?

**Comment by wfreeman-aph** [comment]
@jrbowden Good points again. I'd say the two purposes you mentioned are both possible use cases. I think it's also useful for the reader. Some readers will care more than others but, for some readers, especially students, the information could be critical. The question or teacher may refer to "the yellow highlighted section" or ask them to "define the words in bold" or something like that.

**Comment by jylioja21** [comment]
HTML 5 has new meanings for some of the emphasis elements. For example, <em> means text has vocal emphasis, and <i> means text is set off in some way, but won't necessarily be vocally emphasized. Italics which is for visual formatting only is done with CSS. The <em> and <i> will typically be shown in italics but there are semantic differences for using the tags. There is a similar situation with <strong>, <b>, and bold done with CSS. These differences aren't accounted for by today's screen readers but it is worrth considering when we are trying to follow the current standards.

**Comment by wfreeman-aph** [comment]
@jennifersutton shared this helpful link that covers HTML semantics with screen readers and I'm posting it here for future reference: https://www.tpgi.com/screen-readers-support-for-text-level-html-semantics/.

**Comment by wfreeman-aph** [comment]
Proposal is to use em for italics, strong for bold, u for underline, and mark for other kinds of generic kinds of emphasis. Jennifer Sutton mentions that screen readers don't tend to support mark and we should take that into account.

Issue is brought up about hiding braille characters if they are already included and not added by the markup. It's not impossible for reading systems to do that but we need to consider options. One suggestion is to wrap the braille characters in a span. The issue with that suggestion is it would add a lot of bloat to the file but may not add much benefit. Issue #17 will need to be revisited at a later time.

Charles mentions controversy related to how screen readers implement emphasis. The suggestion then is that you could use em or strong when semantic emphasis is needed and b or i when it is just typographical. You can also add classes to further define what is intended.

Bert mentions that mark should not be used for emphasis. It is not really appropriate. He mentions using a span with a class instead as that gives more semantic information.

After discussion is to use em for italics, strong for bold, and spans with a class for all other kinds of emphasis.

**Comment by bertfrees** [comment]
It helps to look at this requirement from the perspective of the different use cases we've identified, and then combine the solutions. As far as I understand we identified five use cases:

1. for purely semantic purposes
2. for having the possibility to include the styles of the print book within the e-braille file
3. for back-translation
4. for showing/hiding braille indicators that are already present in the content
5. for dynamically inserting braille indicators (when the document contains plain text, or braille but without emphasis indicators)

This is my analysis:

1. Follow the HTML recommendations for marking up emphasized text. More fine-grained semantics could be handled with attributes on the (`em`, `strong`, etc.) elements. The choice of the tags has everything to do with the semantics and is independent of how the text is presented in braille (which indicators are used) and in the print book.
2. This use case can be further split up into two parts: do we just want to be able to make a visual rendering that is faithful to the original print book, or do we also want to be able to convey the same information to the user in a nonvisual way?
   1. The first case is pure styling and CSS is the answer. No specific markup is needed, only elements and attributes to attach CSS styles to (could be spans and classes).
   2. The second case is much more challenging. How to convey e.g. color information without including transcriber notes in the content? How can it be automated? I'm not even sure whether this is an actual requirement or not.
3. You can argue that for back-translation you shouldn't need any markup. Any braille code should allow a computer to recognize the emphasis indicators and not mistake them for something else.
4. One proposal was to enclose the indicators in spans with some class or other attribute that is recognized by the reading system.
5. The solution that makes most sense here is CSS, because braille indicators are the braille counterpart of text styles/decoration. A fixed mapping from certain tags to certain braille indicators (e.g. `em` to italic indicator and `strong` to bold indicator) makes less sense. Firstly because this would conflict with use case 1 (semantics): there is no one-to-one mapping between semantics and indicators. Some braille codes have only one emphasis indicator to indicate all kinds of emphasis with different meanings. Some braille codes provide three, four or more different indicators that can be mapped to different kinds of emphasis and the transcriber determines a suitable mapping. For the same reasons there is also no one-to-one mapping between print styles and braille indicators. Unfortunately CSS currently does not provide a mechanism to specify the braille indicator. DAISY Pipeline supports a custom CSS extension to make this possible, however it is not very portable. An alternative could be to develop a grammar for braille indicators, and specify it through some special attribute.
