### ISSUE TITLE
Allow different CSS to be applied to tags and classes from another braille region

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#90]
Issue #89 suggests that we will have a common method for identifying different kinds of formatting within the HTML. If that is the case, it could be possible to apply different CSS to the same HTML and get different formatting.

An example of this is print and braille page numbers in the UK vs the US. So the UK transcriber's file identifies the print and braille page numbers and then the UK CSS file formats them according to the UK rules and so puts them on the first line of each page. Now in the US, print page numbers go on the first line but braille page numbers go on the last line, so opening this UK file we have where the print and braille numbers are identified but then US CSS would format them according to US rules.

The main issue I can foresee is if places where one region cares about something that the other region doesn't. A simple example of this issue is if one region has four types of headings and the other region has only three types of headings. What do you do with the fourth type of heading in the region with three types? What about the reverse?

What about a more extreme example? What if one region cares about something that another region doesn't even recognize as a kind of formatting? To avoid picking on any one braille region, you could imagine a region that doesn't use headings at all. How do you interpret headings for the non-heading region when the file was generated in a region that does care about headings? How meaningful is a file from the non-heading region in a region that does care about headings?

**Comment by mattgarrish** [comment]
This seems to strike at the bigger problem of regionalized braille. Absent a universal set of formatting rules, we're never going to solve the problems you're suggesting.

Either the users reads the braille as it was produced or they live with whatever limitations come from trying to reformat it.

But it does raise the question of whether we're going down a rabbit hole chasing common classes. Are there enough, and where do we draw the line so that we're not trying to solve the (possibly conflicting) regional formatting of every braille code?

There's perhaps an argument that we should only define html features that html itself doesn't, like running headers, and CSS features/expectations not solved natively. That would leave the classes, styling, etc. for producing regional braille to regional producers to determine, which could be standardized and documented for others in separate specifications (profiles, in effect).

**Comment by wfree-aph** [comment]
This feature will depend on authoring tools and reading systems implementing common CSS and tagging conventions or to implement some kind of conversion process when different tags are encountered. We make recommendations in the Best Practices documents but ultimately do not control what is implemented. Closing this as completed because of those recommendations.
